# Generated by Django 3.2.2 on 2022-04-25 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('resume_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='resume_id')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='resume content')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Template ID')),
                ('thumbnail', models.ImageField(blank=True, default='/placeholder.png', upload_to='thumbnails', verbose_name='template thumbnail')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicResume',
            fields=[
                ('resume_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resume.resume')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Url')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='resume.template'),
        ),
        migrations.CreateModel(
            name='ResumePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.SmallIntegerField(choices=[(0, 'View'), (1, 'Write'), (2, 'Full')], db_index=True, default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
    ]
