# Generated by Django 4.0.1 on 2022-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_allowed_users_alter_resume_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='allowed_users',
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='resume content'),
        ),
    ]
