# Generated by Django 4.0.1 on 2022-01-16 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0004_alter_resumepermission_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepermission',
            name='right',
            field=models.SmallIntegerField(choices=[(0, 'View'), (1, 'Write'), (2, 'Full')], db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='resumepermission',
            unique_together={('user', 'resume')},
        ),
    ]
