# Generated by Django 4.0.1 on 2022-01-16 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resumepermission_right_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_url', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Url')),
                ('resume_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
