# Generated by Django 4.0.1 on 2022-01-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_publicresume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicresume',
            old_name='public_url',
            new_name='public_id',
        ),
    ]
