# Generated by Django 4.0.1 on 2022-01-21 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_publicresume_id_alter_publicresume_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='template',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to='thumbnails', verbose_name='template thumbnail'),
        ),
    ]
