# Generated by Django 4.0.1 on 2022-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_template_created_date_template_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
